name: travel_ai_new
description: AI-powered travel planning app
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0  
  cupertino_icons: ^1.0.2
  flutter_animate: ^4.5.2
  flutter_screenutil: ^5.9.3
  lottie: ^2.7.0
  flutter_svg: ^2.0.9  
  smooth_page_indicator: ^1.1.0 
  cached_network_image: ^3.3.0
  google_fonts: ^6.1.0
  flutter_native_splash: ^2.4.4
  supabase_flutter: ^2.5.6
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.1
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.2
  flutter_dotenv: ^6.0.0
  font_awesome_flutter: ^10.7.0
  uni_links: ^0.5.1
  # State Management - RIVERPOD вместо Provider
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5
  liquid_glass_renderer: ^0.1.1-dev.25
  google_maps_flutter: ^2.5.0
  flutter_map: ^7.0.2  # ✅ ДОБАВЬ ЭТО
  latlong2: ^0.9.1
  phosphor_flutter: ^2.1.0  # ✅ ИСПРАВЛЕНО: конкретная версия
  geolocator: ^11.0.0  # Для получения координат
  geocoding: ^3.0.0    # Для конвертации координат в названия
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  integration_test:
    sdk: flutter
  mocktail: ^1.0.4
  hive_generator: ^2.0.1
  build_runner: ^2.4.9

flutter_native_splash:
  color: "#a3b18a"                    # Цвет фона для светлой темы
  image: assets/icons/splash.png            # Логотип (опционально)
  
  android: true
  ios: true
  web: false
  
  # Дополнительные настройки для Android 12+
  android_12:
    image: assets/splash_android_12.png
    icon_background_color: "#ffffff"
    image_dark: assets/splash_android_12_dark.png
    icon_background_color_dark: "#101924"

flutter:
  uses-material-design: true
  
  # ✅ FONTS - ПЕРЕМЕЩАЕМ СЮДА, ВНУТРЬ СЕКЦИИ flutter:
  fonts:
    - family: NerkoOne-Regular
      fonts:
        - asset: assets/fonts/NerkoOne-Regular.ttf
          weight: 400
        # Если есть другие начертания, добавь их тоже
        # - asset: assets/fonts/warmwinter-Bold.ttf
        #   weight: 700
  
  # ✅ ASSETS - ОСТАЕТСЯ ТУТ ЖЕ
  assets:
    - assets/images/
    - assets/images/continents/
    - assets/icons/
    - assets/fonts/
    - assets/animations/
    - assets/svg/
    - .env
