# splash_config.yaml
color: "#BC986A"
image: "assets/images/logo.png"
splash_icon_background: "#BC986A"
branding_image: "assets/images/logo.png"
animation:
  android: "assets/animations/animation.json"
  ios: "assets/animations/animation.json"
