# splash_config.yaml
color: "#6a994e"
image: "assets/images/logo.png"
splash_icon_background: "#6a994e"
branding_image: "assets/images/logo.png"
animation:
  android: "assets/animations/animation.json"
  ios: "assets/animations/animation.json"
