-- ============================================================================
-- AI-Generated Trips Table
-- Stores trips generated by AI for each user
-- ============================================================================

-- Create ai_generated_trips table
CREATE TABLE IF NOT EXISTS public.ai_generated_trips (
  -- Primary key
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

  -- Foreign key to auth.users
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,

  -- Trip metadata
  title TEXT NOT NULL,
  city TEXT NOT NULL,
  country TEXT,

  -- Trip details
  description TEXT,
  duration_days INTEGER DEFAULT 3,
  price DECIMAL(10, 2),
  currency TEXT DEFAULT 'EUR',

  -- Images
  hero_image_url TEXT,
  images JSONB DEFAULT '[]'::jsonb,

  -- Trip information
  includes JSONB DEFAULT '[]'::jsonb,
  highlights JSONB DEFAULT '[]'::jsonb,
  itinerary JSONB DEFAULT '[]'::jsonb,

  -- Rating and reviews
  rating DECIMAL(2, 1) DEFAULT 4.5,
  reviews INTEGER DEFAULT 0,

  -- Cost estimates
  estimated_cost_min DECIMAL(10, 2),
  estimated_cost_max DECIMAL(10, 2),

  -- Activity information
  activity_type TEXT,
  best_season JSONB DEFAULT '[]'::jsonb,

  -- User interaction
  is_favorite BOOLEAN DEFAULT false,

  -- Original query that generated this trip
  original_query TEXT,

  -- Timestamps
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW(),

  -- Indexes for performance
  CONSTRAINT ai_generated_trips_user_id_idx CHECK (user_id IS NOT NULL)
);

-- ============================================================================
-- Indexes for better query performance
-- ============================================================================

-- Index on user_id for faster user-specific queries
CREATE INDEX IF NOT EXISTS idx_ai_trips_user_id
  ON public.ai_generated_trips(user_id);

-- Index on created_at for sorting by date
CREATE INDEX IF NOT EXISTS idx_ai_trips_created_at
  ON public.ai_generated_trips(created_at DESC);

-- Index on city for location-based searches
CREATE INDEX IF NOT EXISTS idx_ai_trips_city
  ON public.ai_generated_trips(city);

-- Composite index for user favorites
CREATE INDEX IF NOT EXISTS idx_ai_trips_user_favorites
  ON public.ai_generated_trips(user_id, is_favorite)
  WHERE is_favorite = true;

-- ============================================================================
-- Row Level Security (RLS) Policies
-- ============================================================================

-- Enable RLS
ALTER TABLE public.ai_generated_trips ENABLE ROW LEVEL SECURITY;

-- Policy: Users can view only their own trips
CREATE POLICY "Users can view their own AI trips"
  ON public.ai_generated_trips
  FOR SELECT
  USING (auth.uid() = user_id);

-- Policy: Users can insert their own trips
CREATE POLICY "Users can create their own AI trips"
  ON public.ai_generated_trips
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can update only their own trips
CREATE POLICY "Users can update their own AI trips"
  ON public.ai_generated_trips
  FOR UPDATE
  USING (auth.uid() = user_id)
  WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete only their own trips
CREATE POLICY "Users can delete their own AI trips"
  ON public.ai_generated_trips
  FOR DELETE
  USING (auth.uid() = user_id);

-- ============================================================================
-- Trigger for automatic updated_at timestamp
-- ============================================================================

-- Create function to update updated_at timestamp
CREATE OR REPLACE FUNCTION public.update_ai_trips_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

-- Create trigger
DROP TRIGGER IF EXISTS trigger_update_ai_trips_updated_at ON public.ai_generated_trips;
CREATE TRIGGER trigger_update_ai_trips_updated_at
  BEFORE UPDATE ON public.ai_generated_trips
  FOR EACH ROW
  EXECUTE FUNCTION public.update_ai_trips_updated_at();

-- ============================================================================
-- Helper Functions
-- ============================================================================

-- Function to get user's trip count
CREATE OR REPLACE FUNCTION public.get_user_ai_trips_count(p_user_id UUID)
RETURNS INTEGER AS $$
  SELECT COUNT(*)::INTEGER
  FROM public.ai_generated_trips
  WHERE user_id = p_user_id;
$$ LANGUAGE sql SECURITY DEFINER;

-- Function to get user's favorite trips
CREATE OR REPLACE FUNCTION public.get_user_favorite_ai_trips(p_user_id UUID)
RETURNS SETOF public.ai_generated_trips AS $$
  SELECT *
  FROM public.ai_generated_trips
  WHERE user_id = p_user_id AND is_favorite = true
  ORDER BY created_at DESC;
$$ LANGUAGE sql SECURITY DEFINER;

-- ============================================================================
-- Grant permissions
-- ============================================================================

-- Grant usage on schema
GRANT USAGE ON SCHEMA public TO authenticated;

-- Grant permissions on table
GRANT SELECT, INSERT, UPDATE, DELETE ON public.ai_generated_trips TO authenticated;

-- Grant permissions on sequence (for UUID generation)
GRANT USAGE ON ALL SEQUENCES IN SCHEMA public TO authenticated;

-- ============================================================================
-- Comments for documentation
-- ============================================================================

COMMENT ON TABLE public.ai_generated_trips IS 'Stores AI-generated trips for each user';
COMMENT ON COLUMN public.ai_generated_trips.user_id IS 'Reference to the user who generated this trip';
COMMENT ON COLUMN public.ai_generated_trips.itinerary IS 'JSON array of daily itinerary with places and activities';
COMMENT ON COLUMN public.ai_generated_trips.images IS 'JSON array of image URLs for the trip';
COMMENT ON COLUMN public.ai_generated_trips.original_query IS 'The original user query that generated this trip (e.g., "romantic weekend in Paris")';
